version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app-tier
  db:
    image: mysql:8.0.36
    command: --init-file /data/application/init.sql
    container_name: db
    restart: always
    env_file:
      - .env
    volumes:
      - ./app/models/init.sql:/data/application/init.sql
    networks:
      - app-tier
networks:
  app-tier:
    driver: bridge